# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
# https://docs.aws.amazon.com/codebuild/latest/userguide/getting-started-cli-create-build-spec.html
# https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html
# https://docs.aws.amazon.com/codebuild/latest/userguide/runtime-versions.html

version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0

    commands:
      - echo Configure AWS defaults using the configuration script added to the Docker Image.
      - pwsh -command './CodeBuild/configure_aws_credential.ps1'
      - echo Installing PowerShell Modules from S3
      - pwsh -command './CodeBuild/install_modules.ps1'

  pre_build:
    commands:
      - pwsh -command '$PSVersionTable'
      - pwsh -command 'Get-ChildItem env:'
      - echo Pre-Build started on `date`
      - pwsh -command '& ./CodeBuild/IntegrationTest/New-IntegrationInfrastructure.ps1'

  build:
    commands:
      - pwsh -command '
          Import-Module Pester;
          $pesterConfiguration = [PesterConfiguration]::new();
          $pesterConfiguration.Run.Exit = $true;
          $pesterConfiguration.Run.Path = "./CodeBuild/IntegrationTest/Tests";
          $pesterConfiguration.Output.Verbosity = "Detailed";
          Invoke-Pester -Configuration $pesterConfiguration'
    finally:
      - pwsh -command '& ./CodeBuild/IntegrationTest/Remove-IntegrationInfrastructure.ps1'
